![](https://images.velog.io/images/majaeh43/post/dc9f32f0-9eac-479d-b437-5e05952c9ea3/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-10-17%20%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A5%E1%86%AB%2012.24.43.png) 
#### * 이 오류는 DB, 모델을 수정할 경우에 자주 발생해서 까먹지 않으려고 기록을 해본다^ ^

![](https://images.velog.io/images/majaeh43/post/8e8c3f96-a1fb-4459-8c00-16402666e3c3/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-10-17%20%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A5%E1%86%AB%2012.16.57.png)
* makemigraitons 하면서 엄청 뜨는 이 에러^^
* 이 메세지는 필드를 추가/수정 했을 때 뜨는데 만약 필드를 추가했을 경우 원래 저장되어있던 객체들의 새로운 필드에는 어떤 조치를 취해야 하는지 물어보는 메세지라고 보면된다.
```
🪓 name = models.CharField(null=True, default='')
```
#### 에러를 해결하고자
* 나는 해당 필드 옵션에 null=True 옵션을 넣었다.
* 다른 방법으로는 : blank 옵션을 설정하거나 makemigrations를 하면 생성되는 0001_initial.py, 0002~로 시작되는 모듈들을 삭제하고
makemigrations하면 된다.
* 혹은 필드의 default 값을 설정해주면 된다.

완료- ! 🪓

